// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq8x1bQ7AHYILl3SEeXMsUK97Qaaw8FgM',
    appId: '1:496568492043:web:b9124a0f6a6cd5e489270e',
    messagingSenderId: '496568492043',
    projectId: 'calory-tracking-app',
    authDomain: 'calory-tracking-app.firebaseapp.com',
    storageBucket: 'calory-tracking-app.firebasestorage.app',
    measurementId: 'G-N2KY9DR9ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgad3IadvPt4xJt-xBWZRMp-ZvPV9-UHI',
    appId: '1:496568492043:android:41e5c734c5885e6489270e',
    messagingSenderId: '496568492043',
    projectId: 'calory-tracking-app',
    storageBucket: 'calory-tracking-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjZoy4ca-YV676CPYJISDvMOPHkKYDF2k',
    appId: '1:496568492043:ios:d616f5c626b55c4989270e',
    messagingSenderId: '496568492043',
    projectId: 'calory-tracking-app',
    storageBucket: 'calory-tracking-app.firebasestorage.app',
    iosBundleId: 'com.calotrack.calotrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjZoy4ca-YV676CPYJISDvMOPHkKYDF2k',
    appId: '1:496568492043:ios:d616f5c626b55c4989270e',
    messagingSenderId: '496568492043',
    projectId: 'calory-tracking-app',
    storageBucket: 'calory-tracking-app.firebasestorage.app',
    iosBundleId: 'com.calotrack.calotrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq8x1bQ7AHYILl3SEeXMsUK97Qaaw8FgM',
    appId: '1:496568492043:web:3f785fdaafab710a89270e',
    messagingSenderId: '496568492043',
    projectId: 'calory-tracking-app',
    authDomain: 'calory-tracking-app.firebaseapp.com',
    storageBucket: 'calory-tracking-app.firebasestorage.app',
    measurementId: 'G-MW32X23BR2',
  );
}
